### PR TITLE
Geo fix and cluster region bounds

### PR DESCRIPTION
**Pull request by Brianggalvez**
- Fixed an error in the initial configuration where the module attempted to load from Alloy.CFG.geo instead of Alloy.CFG.T.geo

- Added config.clusterRegionBounds to indicate if the user wants to compute the region the cluster is clustering.

### CODE REVIEW

**Comment by kopiro** [comment]
Sorry @Brianggalvez , i don't see any commits for this PR.
Can you just re push?

**Comment by Brianggalvez** [comment]
@kopiro  done!

**Comment by kopiro** [comment]
Uhm.. there are too many changes. Maybe you changed tabs?

**Comment by kopiro** [comment]
Sorry @Brianggalvez - the problem is that I see our commits; dunno why.
Can you reopen another PR?

image

Sorry about that.

**Comment by Brianggalvez** [comment]
no problem

**Pull request closed without merging**
